<?php

class team extends head{

    public function setFullName($full_name)
    {
        parent::setFullName($full_name); // TODO: Change the autogenerated stub
    }

    public function getFullName()
    {

        return parent::getFullName(); // TODO: Change the autogenerated stub
    }
    public function setPosition($position)
    {
        echo "<h2 id = 'team'>They are $position of this website</h2>";
        parent::setPosition($position); // TODO: Change the autogenerated stub
    }

    public function members($name1,$name2,$name3){
        echo "<p id = 'team'>This is the newest online supermarket project to PHP final</p>";
        echo "<p id='team'>$name1,$name2,$name3 are creators. The website is one of the big project at first academic year</p>";
    }
    public function advice(){
        echo "<p>Real food is whole, single-ingredient food.It is mostly unprocessed, free of chemical additives, and rich in nutrients.
                 In essence, it's the type of food human beings ate exclusively for thousands of years.
                 However, since processed foods became popular in the 20th century, the Western diet has shifted toward ready-to-eat meals.
                 While processed foods are convenient, they also harm your health. In fact, following a diet based on real food may be one
                 of the most important things you can do to maintain good health and a high quality of life.</p>";
    }
}
?>


